### ISSUE TITLE
Match a Field Without Specifying Array Index

### ISSUE THREAD

**Issue by ziege** [thomas4019/mongo-query-to-postgres-jsonb#1]
I think this is what you're looking for:
SELECT \* FROM (SELECT e.value FROM test t, jsonb_array_elements(t.test#>'{memos}') e) v WHERE v.value->>'by' = 'shipping'

(Tested with the MongoDB exmaple: https://docs.mongodb.com/manual/tutorial/query-documents/#match-a-field-without-specifying-array-index)

**Comment by thomas4019** [comment]
Thanks for this! I hadn't thought of using a subquery. 

Another tricky thing is identifying if this should be done or if the basic equality match is needed. Maybe the query could use jsonb_typeof and a case statement to conditionally do this if the field is an array?

I'm also confused about how array based matching should work on even deeper queries. E.g. find( { 'companies.memos.by': 'shipping' } )

**Comment by brandonros** [comment]
Preface: I have a production app stuck on Mongo and I'm about to try utilizing this package (obviously with some work and testing) to save it.

For anybody who may need this, I expanded on @ziege's example:

`create table tbl(col jsonb);`

`insert into tbl(col) VALUES('{"memos":[{ "by": "shipping" }]}');`

```
SELECT * FROM
    (SELECT e.value FROM tbl tbl, jsonb_array_elements(tbl.col#>'{memos}') e) v
    WHERE v.value->>'by' = 'shipping';
```

**Comment by brandonros** [comment]
@thomas4019 since I need this and I need it semi-quickly, a really dirty hack could be to pass an array (or Set to be efficient, I guess) to `mongoToPostgres` as a third parameter called "known subdocument/array field names". That ought to solve that issue.

**Comment by thomas4019** [comment]
@ziege and @brandonros, thanks for the great ideas. I've added support for both in the latest version.
