### ISSUE TITLE
Create a read-only mode (or submodule)

### ISSUE THREAD

**Issue by mattbishop** [thomas4019/mongo-query-to-postgres-jsonb#11]
I'd like to use mongo queries that **only read, never update,** the underlying database. I don't know if it would be simpler to have a submodule like `readonly.js` that contains the read-only transformers, and the main module imports that and adds the update commands?

**Comment by mattbishop** [comment]
I'm going to close this as I haven't read the docs well enough to find the `convertSelect()` method.  :embarrassing:

**Comment by thomas4019** [comment]
No worries, I'm glad you found what you're looking for 😅
