### ISSUE TITLE
[Question] using in browser?

### ISSUE THREAD

**Issue by swuecho** [thomas4019/mongo-query-to-postgres-jsonb#16]
so a live demo could be possible and can be used as a jsonb query editor.  Thanks!

**Comment by thomas4019** [comment]
Hi @swuecho, with the latest version I just packaged a file that can be used in the browser easily. So now you can just import something like `https://unpkg.com/mongo-query-to-postgres-jsonb@0.2.13/dist/m-to-psql.js` and then use window.mToPsql as described in the docs.

**Comment by swuecho** [comment]
Thanks!  I made a web page using the 0.2.13. if anyone want to play with it.  here is the link: https://www.bestqa.net/sr/bestqa_demo_msql
