### ISSUE TITLE
$nor, $exists, $size

### ISSUE THREAD

**Issue by brandonros** [thomas4019/mongo-query-to-postgres-jsonb#2]
Posting this because I found it slightly funny.

![image](https://cloud.githubusercontent.com/assets/8949910/15982103/cd7dbfea-2f4d-11e6-90aa-51a3cb60896f.png)

I have a query that has all 3 currently not supported operators in one. :)

**Comment by brandonros** [comment]
I'll see what work I can do to get these done.

**Comment by thomas4019** [comment]
Wow, that is a very unsupported query currently!

$size: should be pretty easy using json_array_length.
$exists: I think you can just append "IS NOT NULL" e.g. data->'some'->'field' IS NOT NULL. It looks like the jsonb null doesn't match postgres' null so this should conform to the postgres spec that $exists matches null fields.

Let me know if you need any help.

**Comment by thomas4019** [comment]
I know this is quite late, but I finally got around to adding support for these query types.

**Comment by brandonros** [comment]
Super impressive followup man. :)
