### ISSUE TITLE
Single quote not escaped in update query

### ISSUE THREAD

**Issue by vyacheslav-sozap** [thomas4019/mongo-query-to-postgres-jsonb#20]
This call
```
mToPsql.convertUpdate('value', { $set: { prop_1: {
	message:"I'm ok"
} } }, false)
```
gives following result:
```
`jsonb_set(value,'{prop_1}','{"message":"I'm ok"}'::jsonb)`
```

Here we have not escaped single quote inside a single quote string, which will give an a error if used, probably, shouldn't be that way.

**Comment by pete-rai** [comment]
Hey Thomas, we also came across this issue. I see you have a fix, but that does not seem to have made it into a published package. Can you push out a version to NPM with this fix in please?

**Comment by thomas4019** [comment]
@pete-rai For sure! I just published `0.2.15` which has the fix. Let me know if you run into any issues. Thanks!

**Comment by pete-rai** [comment]
Many thanks Thomas! :D

**Comment by pete-rai** [comment]
Unfortualtely this fix did not work under all circumstances. In the end, i escaped quotes in all strings in the query object using: 

```
typeof item === 'string' ? item.replace(/'/g, "''").replace(/\"/g, "\\\"") : item
```

This fix worked for all our tests

**Comment by thomas4019** [comment]
Good to know @pete-rai, can you provide an example that failed so I can add to the testing suite and fix?
