### ISSUE TITLE
Make this a complete production drop-in replacement for MongoDB

### ISSUE THREAD

**Issue by brandonros** [thomas4019/mongo-query-to-postgres-jsonb#3]
Things I see missing:
- [x] Project fields on queries (instead of SELECT *)
- [ ] find options like $limit, $skip, $sort
- [ ] ObjectId generator? (kind of silly)
- [ ] insert
- [x] update
- [ ] upsert
- [ ] remove

**Comment by thomas4019** [comment]
Thanks for making this list. The trickiest one here is update as support for modifying part of documents. A bad but easy solution is to do a select, use [mongo-query](https://github.com/Automattic/mongo-query) to do the update, and then update the complete document in postgres. This causes you to lose atomic updates and isn't very efficient.

In PostgreSQL 9.5 they've added [jsonb_set](https://www.postgresql.org/docs/9.5/static/functions-json.html#FUNCTIONS-JSON-PROCESSING-TABLE) which lets you modify one field at a time. These could be chained to update several fields in one query.

I'm not sure if this module should be changed to add all these features or a new module should be created which uses this as a dependency. I think it would be really cool to create a library that matches Mongo's node library so you could just replace the library to migrate.

**Comment by thomas4019** [comment]
@brandonros, thanks for the suggestion! In the past few months I've added support for projections, converting sort and updates queries and more. I've decided the full drop-in replacement should be in a new project, currently called [pgmongo](https://github.com/thomas4019/pgmongo). It mimics a MongoDB server, but is still very much a work in progress currently.
