### ISSUE TITLE
Error using $nin

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/mongo-query-to-postgres-jsonb#33]
I am trying to convert the following mongo query but getting a syntax error from postgres

Query:

```js
'$exists': true,
'$nin': [
  null,
  undefined,
  ''
],
```

The query is intended to return all documents where property exists but the value is not falsey.

Error:
![image](https://github.com/thomas4019/mongo-query-to-postgres-jsonb/assets/23186829/e7b97dbd-f8b1-4726-b731-5cdeefdfb9fa)

**Comment by kane-mason** [comment]
Dont think its actually related to `$nin` since is also happens using `$not: { $in:`

**Comment by thomas4019** [comment]
Thanks for bringing this up. I've pushed a fix and pushed out a new release. Note that including `undefined` in the $nin list probably isn't doing anything should MongoDB shouldn't let you store undefined values (that would be the same as it not being set). Please let me know if the latest code doesn't work as expected for you. Thanks!

**Comment by kane-mason** [comment]
Thanks so much will check it out!
