### ISSUE TITLE
orderby for numbers does not work

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/mongo-query-to-postgres-jsonb#35]
Lets say I have a property `index` and its type is `number`

If I attempt to `orderby` it will treat the field as if its a `string`

ie my sorted results will look like this:

1
10
11
2
3
4
5
etc

Of course I want a numberic sort

1
2
3
4
5
...
9
10
11

**Comment by thomas4019** [comment]
Ahh, interesting. I probably need to add support for the `numericOrdering` collation option

**Comment by thomas4019** [comment]
Turns out this is already supported using the `forceNumericSort` option:
https://github.com/thomas4019/mongo-query-to-postgres-jsonb?tab=readme-ov-file#mtopsqlconvertsortsqlfield-sortquery-forcenumericsort

**Comment by kane-mason** [comment]
Ah so maybe then it’s actually a case of within expressa forcing numeric sort when the targeted property is type number?

**Comment by thomas4019** [comment]
Yeah, [this line](https://github.com/thomas4019/expressa/blob/0113a7fc16d2e8acbceb447664e3f52b2456066f/db/postgres.js#L23C23-L23C45) would need to be changed. Looks like Expressa isn't using the `convertSort` helper from this library but instead using it's own helper function currently.

**Comment by kane-mason** [comment]
@thomas4019 could you help me with this please? Worried to break something

**Comment by thomas4019** [comment]
Note: this issue is fixed in Expressa now
