### ISSUE TITLE
unexpected $in behavior

### ISSUE THREAD

**Issue by coderofsalvation** [thomas4019/mongo-query-to-postgres-jsonb#4]
this (somewhat expressa related) url:

    req.url = /users?query={"$and":[{"roles":{"$in":["Anonymous"]}}]}&orderby={"meta.created":-1}&limit=30

translates into

    SELECT * FROM users WHERE (data->>'roles' IN ('Anonymous')) ORDER BY data->'meta'->>'created' DESC LIMIT 30

however this returns 0 results..while this (manually entered) postgres (v9.5) query :

    SELECT * FROM users WHERE (data->'roles')::jsonb ? 'Anonymous'

does return results (as expected).
I tried $elemMatch as well but it has the same issue.

> any idea why ?

**Comment by thomas4019** [comment]
Hmm, I think I'll need to make some changes to make a query like this work, possible using jsonb_array_elements. I'm surprised I hadn't seen this before. 

As a short term solution if user's with the Anonymous role only have 1 role then the following query should work.
query={"roles":["Anonymous"]}

Or if you know the user only has a fixed number of roles this query will work, but is pretty bad.
query={"$or":[{"roles.0":"Anonymous"},{"roles.1":"Anonymous"},{"roles.2":"Anonymous"}]}

**Comment by coderofsalvation** [comment]
Thanks for the quick response.
No worries, we'll get there.
Luckily i can easily perform custom sql-queries with the express postgres
adapter, which is exactly why i switched to it.

Leon

On Fri, Jan 26, 2018 at 5:59 AM, Me via Boomerang <leonvankammen@gmail.com>
wrote:

> Message moved to top of Inbox by Boomerang (view this conversation
> <https://mail.google.com/mail/?shva=1#all/1612e74017163a44>).
>
> Don't want this notification email in the future? Go to
> https://b4g.baydin.com/settings and uncheck the 'At the top of your
> Inbox' option under Settings. Please note that your Boomeranged messages
> would no longer return to the top of your Inbox.
>



-- 
/WEBSITE    2wa.isvery.ninja
/MOBILE     +31 6 13499604
/LOCATION   Netherlands, Drachten. Hongarije, Budapest.
/COMPANYNR. 08124656
/TAGS       Rapid Prototyping of ideas/concepts using JavaScript,
            Node.js, OpenSource. Growth-hacking partnerships,
            lead scraping partnerships.

**Comment by thomas4019** [comment]
Hi Leon,
I've recently fixed this issue in master. Unfortunately, since $in can take an array, it seems the best way to do it requires the converter to know that roles is an array field so that it can do a union operation (via a subquery). So to do this right you'd need to specify the list of array fields as explained in the readme [here](https://github.com/thomas4019/mongo-query-to-postgres-jsonb#select-match-a-field-without-specifying-array-index).
